version: '3.4'

networks:
  net:

volumes:
  hexchan_pg_data:
    driver: local
  hexchan_app_data:
    driver: local


services:
  db:
    image: postgres:11-alpine
    container_name: hexchan_db
    restart: always
    environment:
      - POSTGRES_DB=hexchan
      - POSTGRES_USER=hexchan
      - POSTGRES_PASSWORD=hexchan
    networks:
      - net
    volumes:
      - hexchan_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      - net
    ports:
      - 8080:8080

  app:
    build: .
    image: hexchan
    container_name: hexchan_app
    restart: always
    environment:
      - FAKE_CONTENT=False
      - DEBUG=False
      - DB_HOST=hexchan_db
      - DB_PORT=5432
      - DB_NAME=hexchan
      - DB_USER=hexchan
      - DB_PASSWORD=hexchan
#      - AWS_ACCESS_KEY_ID=
#      - AWS_SECRET_ACCESS_KEY=
#      - AWS_STORAGE_BUCKET_NAME=
    volumes:
      - hexchan_app_data:/app/uploads

    ports:
      - 80:80
      - 443:443
    networks:
      - net
    depends_on:
      - db
    links:
      - db